backend:
  name: github
  repo: flumoh/flumoh.github.io
  branch: main
  site_domain: brilliant-fudge-9f6632.netlify.com

publish_mode: editorial_workflow

# site_url: flumoh.github.io
# display_url: flumoh.github.io
logo_url: https://tokens.dougrich.net/api/token/HdzzA-XnpQ.svg
show_preview_links: false
search: false

media_folder: "images/uploads"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - label: "Metadata"
    name: "metadata"
    files:
      - label: "Categories" 
        name: "categories"
        file: "_data/categories.yml"
        fields: 
          - label: "Category"
            name: "category"
            widget: "list"
            allow_add: true
            add_to_top: true
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {Label: "Path", name: "path", widget: "string"}
              - {label: "Description", name: "desc", widget: "markdown"}
      - label: "Tags"
        name: "tags"
        file: "_data/tags.yml"
        fields:
          - label: "Tag"
            name: "tag"
            widget: "list"
            allow_add: true
            add_to_top: true
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {Label: "Color", name: "color", widget: "color"}
              - {label: "Description", name: "desc", widget: "markdown"}
      
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {name: "permalink", value: "/:categories/:year/:month/:day/:title:output_ext"}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        value_field: "category.*"
        search_fields: "category.name"
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_site/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    filter: {name: "permalink", value: "/:categories/:year/:month/:day/:title:output_ext"}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Kategory", name: "category", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Picture", name: "picture", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  

